# Generated by Django 4.0.2 on 2022-02-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=b'I01\n', choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kid'), ('A', 'All')], max_length=2, null=b'I01\n'),
        ),
    ]
